packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@milaboratories/ts-builder': ^1.2.1
  '@milaboratories/ts-configs': ^1.2.0
  '@milaboratories/build-configs': ^1.2.1
  '@milaboratories/pl-model-common': ^1.21.10
  '@platforma-sdk/workflow-tengo': ^5.7.3
  '@platforma-sdk/model': ^1.48.4
  '@platforma-sdk/ui-vue': ^1.48.8
  '@platforma-sdk/tengo-builder': ^2.4.2
  '@platforma-sdk/package-builder': ^3.10.7
  '@platforma-sdk/block-tools': ^2.6.27
  '@platforma-sdk/eslint-config': ^1.2.0

  '@platforma-sdk/test': ^1.37.0
  '@milaboratories/helpers': ^1.12.1

  '@platforma-open/milaboratories.runenv-python-3': ^1.1.16
  '@platforma-open/milaboratories.software-ptransform': ^1.4.3

  '@platforma-open/milaboratories.software-binary-collection.software-7zip': ^1.1.2

  'vue': ^3

  'canonicalize': ~2.1.0
  'lodash': ^4.17.17
  '@types/lodash': ^4.17.20

  'typescript': ~5.6.3
  'turbo': ^2.5.4
  'eslint': ^9.30.1
  'vitest': ^2.1.9

  '@vueuse/core': ^13.5.0

  'ag-grid-enterprise': &ag-grid ~33.3.2
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.29.5

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.12.3
  '@platforma-open/milaboratories.samples-and-data.model': ^2.4.1
  '@platforma-open/milaboratories.mixcr-clonotyping-2': ^2.12.27
  '@platforma-open/milaboratories.mixcr-clonotyping-2.model': ^1.20.0
