packages:
  - software/annotator
  - software/annotation2filters
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@milaboratories/ts-configs': ^1.0.4
  '@milaboratories/build-configs': ^1.0.4
  '@platforma-sdk/workflow-tengo': ^4.9.3
  '@platforma-sdk/model': ^1.39.7
  '@platforma-sdk/ui-vue': ^1.39.7
  '@platforma-sdk/tengo-builder': ^2.1.12
  '@platforma-sdk/package-builder': ^2.16.2
  '@platforma-sdk/block-tools': ^2.5.66
  '@platforma-sdk/eslint-config': ^1.0.3

  '@platforma-sdk/test': ^1.39.7
  '@milaboratories/helpers': ^1.6.17

  '@platforma-open/milaboratories.runenv-python-3': ^1.1.16
  '@platforma-open/milaboratories.software-ptransform': ^1.4.3

  '@platforma-open/milaboratories.software-binary-collection.software-7zip': ^1.1.2

  'vue': ^3.5.16
  'vue-tsc': ^2.2.10

  'canonicalize': ~2.1.0
  'lodash': ^4.17.17
  '@types/lodash': ^4.17.20

  'zod': ~3.23.8
  'utility-types': ^3.11.0
  'remeda': ^2.25.0

  'typescript': ~5.6.3
  'tsup': ~8.3.5
  'turbo': ^2.5.4
  'eslint': ^9.30.1

  'vite': ^6.3.5
  'vitest': ^2.1.9
  '@vitejs/plugin-vue': ^5.2.4
  'rollup-plugin-sourcemaps2': ^0.5.2

  '@vueuse/core': ^13.5.0

  'ag-grid-enterprise': &ag-grid ~33.3.2
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.29.5

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.10.7
  '@platforma-open/milaboratories.samples-and-data.model': ^1.10.0
  '@platforma-open/milaboratories.mixcr-clonotyping-2': ^2.8.2
  '@platforma-open/milaboratories.mixcr-clonotyping-2.model': ^1.13.0
