packages:
  - software/annotator
  - software/annotation2filters
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/workflow-tengo': ^4.6.5
  '@platforma-sdk/model': ^1.32.1
  '@platforma-sdk/ui-vue': ^1.32.2
  '@platforma-sdk/tengo-builder': ^2.1.6
  '@platforma-sdk/package-builder': ^2.16.0
  '@platforma-sdk/block-tools': ^2.5.51
  '@platforma-sdk/eslint-config': ^1.0.3

  '@platforma-sdk/test': ^1.32.6
  '@milaboratories/helpers': ^1.6.11

  '@platforma-open/milaboratories.runenv-python-3': ^1.1.16
  '@platforma-open/milaboratories.software-mixcr': 4.7.0-147-develop	
  '@platforma-open/milaboratories.software-ptransform': ^1.4.3

  'vue': ^3.5.16
  'vue-tsc': ^2.2.10

  'canonicalize': ~2.1.0
  'lodash': ^4.17.15
  '@types/lodash': ^4.17.17

  'zod': ~3.23.8
  'utility-types': ^3.11.0
  'remeda': ^2.22.3

  'typescript': ~5.5.4
  'tsup': ~8.1.2
  'turbo': ^2.5.3
  'eslint': ^9.27.0

  'vite': ^6.3.5
  'vitest': ^2.1.9
  '@vitejs/plugin-vue': ^5.2.4
  'rollup-plugin-sourcemaps2': ^0.5.2

  '@vueuse/core': ^13.3.0

  'ag-grid-enterprise': &ag-grid ^33.1.1
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.29.4

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.10.5
  '@platforma-open/milaboratories.samples-and-data.model': ^1.10.0
  '@platforma-open/milaboratories.mixcr-clonotyping-2': ^2.5.1
  '@platforma-open/milaboratories.mixcr-clonotyping-2.model': ^1.11.1
