packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@milaboratories/ts-builder': ^1.0.5
  '@milaboratories/ts-configs': ^1.0.6
  '@milaboratories/build-configs': ^1.0.8
  '@platforma-sdk/workflow-tengo': ^5.6.3
  '@platforma-sdk/model': ^1.45.0
  '@platforma-sdk/ui-vue': ^1.45.0
  '@platforma-sdk/tengo-builder': ^2.3.3
  '@platforma-sdk/package-builder': ^3.10.6
  '@platforma-sdk/block-tools': ^2.6.25
  '@platforma-sdk/eslint-config': ^1.1.0
  '@platforma-sdk/blocks-deps-updater': ^2.0.0

  '@platforma-sdk/test': ^1.45.1
  '@milaboratories/helpers': ^1.12.0

  '@platforma-open/milaboratories.runenv-python-3': ^1.7.5
  '@platforma-open/milaboratories.software-ptransform': ^1.4.3

  '@platforma-open/milaboratories.software-binary-collection.software-7zip': ^1.1.2

  'vue': 3.5.13

  'canonicalize': ~2.1.0
  'lodash': ^4.17.17
  '@types/lodash': ^4.17.20

  'typescript': ~5.6.3
  'turbo': ^2.5.4
  'eslint': ^9.30.1
  'vitest': ^2.1.9

  '@vueuse/core': ^13.5.0

  'ag-grid-enterprise': &ag-grid ~33.3.2
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.29.5

  # other blocks used in tests

  '@platforma-open/milaboratories.samples-and-data': ^1.10.7
  '@platforma-open/milaboratories.samples-and-data.model': ^1.10.0
  '@platforma-open/milaboratories.mixcr-clonotyping-2': ^2.8.2
  '@platforma-open/milaboratories.mixcr-clonotyping-2.model': ^1.13.0
